#
# Common helpers shared by QEMU-based expect test runners.
#

proc parse_common_args {} {
	set myargs $::argv
	while {[llength $myargs]} {
		set myargs [lassign $myargs arg]
		switch -exact -- $arg {
			"--tests"	{set myargs [lassign $myargs ::tests]}
			"--timeout"	{set myargs [lassign $myargs ::timeout]}
			"-q"		{set ::quiet 1}
			"--continue-on-fail" {set ::continue_on_fail 1}
			"--xtest-args"	{set myargs [lassign $myargs ::xtest_args]}
		}
	}
}

proc info arg {
	if {$::quiet == 1} { return }
	puts -nonewline $arg
	flush stdout
}

proc fail_with_message {msg code} {
	info "$msg\n"
	exit $code
}

proc check_test_result {{tee_core_id ""}} {
	set casenum "none"
	set star 0
	set ncases 0
	set nerrors 0
	if {$tee_core_id eq ""} {
		expect {
			-re {  ([^ ]+) FAIL} {
				info " FAIL $expect_out(1,string) (last test started: $casenum)\n"
				incr nerrors
				if {$::continue_on_fail} {
					exp_continue
				}
				exit 1
			}
			-re {rcu.*detected stalls} {
				info " Kernel error: '$expect_out(0,string)' (last test started: $casenum)\n"
				incr nerrors
				if {$::continue_on_fail} {
					exp_continue
				}
				exit 1
			}
			-re {(^|[\r\n])([\*o]) ([^ \r\n]+) } {
				set casenum $expect_out(3,string)
				if {$expect_out(2,string) == "o"} {
					if {$star == 1} {
						set star 0
						exp_continue
					}
				} else {
					set star 1
				}
				if {$::print_test_names} {
					info "# $casenum\n"
				} else {
					info "#"
					if {$ncases % 50 == 49} { info "\n" }
				}
				incr ncases
				exp_continue
			}
			"+-----------------------------------------------------\r\r" {}
			-re {(..TC:[^\n]*assertion[^\n]*failed at[^\n]*)} {
				info "!!! $expect_out(1,string) (last test started: $casenum)\n"
				incr nerrors
				if {$::continue_on_fail} {
					exp_continue
				}
				exit 1
			}
			-re {(..TC:[^\n]*Panic at[^\n]*)} {
				info "!!! $expect_out(1,string) (last test started: $casenum)\n"
				incr nerrors
				if {$::continue_on_fail} {
					exp_continue
				}
				exit 1
			}
			timeout {
				info "!!! Timeout\n"
				info "TIMEOUT - test case too long or hung? (last test started: $casenum)\n"
				exit 2
			}
		}
	} else {
		expect {
			-re {  ([^ ]+) FAIL} {
				info " FAIL $expect_out(1,string) (last test started: $casenum)\n"
				incr nerrors
				if {$::continue_on_fail} {
					exp_continue
				}
				exit 1
			}
			-re {rcu.*detected stalls} {
				info " Kernel error: '$expect_out(0,string)' (last test started: $casenum)\n"
				incr nerrors
				if {$::continue_on_fail} {
					exp_continue
				}
				exit 1
			}
			-re {(^|[\r\n])([\*o]) ([^ \r\n]+) } {
				set casenum $expect_out(3,string)
				if {$expect_out(2,string) == "o"} {
					if {$star == 1} {
						# Do not count first subcase ('o') since start
						# of test ('*') was counted already
						set star 0
						exp_continue
					}
				} else {
					set star 1
				}
				if {$::print_test_names} {
					info "# $casenum\n"
				} else {
					info "#"
					if {$ncases % 50 == 49} { info "\n" }
				}
				incr ncases
				exp_continue
			}
			"+-----------------------------------------------------\r\r" {}
			-i $tee_core_id -re {(..TC:[^\n]*assertion[^\n]*failed at[^\n]*)} {
				info "!!! $expect_out(1,string) (last test started: $casenum)\n"
				incr nerrors
				if {$::continue_on_fail} {
					exp_continue
				}
				exit 1
			}
			-i $tee_core_id -re {(..TC:[^\n]*Panic at[^\n]*)} {
				info "!!! $expect_out(1,string) (last test started: $casenum)\n"
				incr nerrors
				if {$::continue_on_fail} {
					exp_continue
				}
				exit 1
			}
			timeout {
				info "!!! Timeout\n"
				info "TIMEOUT - test case too long or hung? (last test started: $casenum)\n"
				exit 2
			}
		}
	}
	if {$nerrors > 0} {
		info "\nStatus: FAIL ($nerrors errors, $ncases test cases)\n"
		exit 1
	}
	info "\nStatus: PASS ($ncases test cases)\n"
}
